name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      env:
        token: ${{ secrets.TOKEN }}
        multiversus_token: ${{ secrets.MULTIVERSUS_TOKEN }}
        clientId: ${{ secrets.CLIENTID }}
        guildId: ${{ secrets.GUILDID }}
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master        
        - run: flyctl wireguard websockets enable
        - run: flyctl deploy --remote-only
